service: folks

image: lumishq/folks

servers:
  web:
    - folkscommunity

proxy:
  ssl: true
  host: folkscommunity.com
  app_port: 3000
  forward_headers: true
  healthcheck:
    interval: 5
    path: /api
    timeout: 3

registry:
  username: <%= %x(echo $KAMAL_REGISTRY_USERNAME).strip %>
  password:
    - KAMAL_REGISTRY_PASSWORD

builder:
  arch: amd64
  args:
    SENTRY_AUTH_TOKEN: <%= %x(echo $SENTRY_AUTH_TOKEN).strip %>
    VERCEL_URL: folkscommunity.com
  cache:
    type: registry

env:
  secret:
    - VERCEL_URL
    - DATABASE_URL
    - REDIS_URL
    - JWT_SECRET
    - AWS_ACCESS_KEY_ID
    - AWS_SECRET_ACCESS_KEY
    - R2_ACCESS_KEY_ID
    - R2_SECRET_ACCESS_KEY
    - AWS_BUCKET
    - AWS_REGION
    - CDN_URL
    - DISCORD_WEBHOOK_URL
    - NEXT_PUBLIC_VAPID_PUBLIC_KEY
    - VAPID_PRIVATE_KEY
    - APN_AUTH_KEY
    - APN_KEY_ID
    - APN_TEAM_ID
    - APN_TOPIC
    - R2_ACCOUNT_ID
    - RESEND_API_KEY
